services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: ["uvicorn", "src.server:app", "--no-access-log", "--reload", "--host=0.0.0.0"]

  www:
    build: www
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - ./www:/app
    command: ["npm", "run", "dev", "--", "--host=0.0.0.0"]
